/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-05-28 02:29:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.payments;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/payments/../styles/payment.css", Long.valueOf(1622115603186L));
    _jspx_dependants.put("jar:file:/D:/AmilaSLIIT/2020eclipsprojects/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OMT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1622110055988L));
    _jspx_dependants.put("/payments/../styles/Default.css", Long.valueOf(1622163719564L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../styles/Default.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../styles/payment.css\">\r\n");
      out.write("	<style>\r\n");
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  font-family: roboto, sans-serif;\r\n");
      out.write("  background-image: linear-gradient(#ff6963,black,black);\r\n");
      out.write("  \r\n");
      out.write("  background-repeat: repeat;\r\n");
      out.write("  background-attachment: fixed;\r\n");
      out.write("  background-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*start of header*/\r\n");
      out.write("#mainHeader {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  display:flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  padding: 0px 10px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  position:fixed;\r\n");
      out.write("  top: 0px;\r\n");
      out.write("  background: #eee;\r\n");
      out.write("  transition: background 0.4s;\r\n");
      out.write("  z-index: +1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainHeader.is-sticky {\r\n");
      out.write("  background: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainHeader.is-sticky a {\r\n");
      out.write("  color:#eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainHeader.is-sticky .logo img {\r\n");
      out.write("  height:64px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainHeader.is-sticky .Plogo img {\r\n");
      out.write("  margin-top:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainHeader.is-sticky .SearchPadding {\r\n");
      out.write("  padding:5px 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".logo img {\r\n");
      out.write("  height: 84px;\r\n");
      out.write("  transition: height 0.4s;\r\n");
      out.write("}\r\n");
      out.write(".Plogo img {\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  margin-top:18px;\r\n");
      out.write("  transition:0.4s;\r\n");
      out.write("}\r\n");
      out.write("#mainHeader .SearchPadding{\r\n");
      out.write("	padding:10px 10px;\r\n");
      out.write("	transition:0.4s;\r\n");
      out.write("}\r\n");
      out.write("#mainHeader .searchForm {\r\n");
      out.write("  float: middle;\r\n");
      out.write("  padding: 6px 20px;\r\n");
      out.write("  margin-top: 15px;\r\n");
      out.write("  background: none;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer; \r\n");
      out.write("  display:flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchTxt\r\n");
      out.write("{\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 5.5px 10px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  width:400px;\r\n");
      out.write("}\r\n");
      out.write(".searchBT:hover {\r\n");
      out.write("  background-color:#66ff66;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchBT {\r\n");
      out.write("  background-color: #00cc00;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*End of header*/\r\n");
      out.write("\r\n");
      out.write("/* start editing horizontal menu*/\r\n");
      out.write("#menu {\r\n");
      out.write("	 margin-top: 84px;\r\n");
      out.write("	 width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul.menu {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li.menu1 {\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("li.menu2 {\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu li a   {\r\n");
      out.write("	/* When you have li and a together this will work*/\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change the link color to pink on hover \r\n");
      out.write("When you move the curser to a menu item it will highlighted with pink*/\r\n");
      out.write("#menu  li a:hover {\r\n");
      out.write("  background-color: gray;\r\n");
      out.write("}\r\n");
      out.write("/*============================================================================*/\r\n");
      out.write("/*Start of footer*/\r\n");
      out.write("\r\n");
      out.write("div.Bfooter{\r\n");
      out.write("	display:table;\r\n");
      out.write("	width:100%;\r\n");
      out.write("	height:auto;\r\n");
      out.write("}\r\n");
      out.write("#mainFooter {\r\n");
      out.write("  display:flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  bottom:0px;\r\n");
      out.write("  padding:10px 30px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: rgb(100, 100, 100);\r\n");
      out.write("  color:white;\r\n");
      out.write("  position:fixed;\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("#mainFooter .FtopPadding{\r\n");
      out.write("	padding-top:10px;\r\n");
      out.write("}\r\n");
      out.write(".SocialLogos img {\r\n");
      out.write("\r\n");
      out.write("	width:30px;\r\n");
      out.write("	height:30px;\r\n");
      out.write("}\r\n");
      out.write("#mainFooter ul.SocialLogos {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding:0;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("#mainFooter li.SocialLogos {\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("#mainFooter li a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".DateandTime{\r\n");
      out.write("	font-family:\"Arial Black\", Gadget, sans-serif;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".copyRSing{\r\n");
      out.write("	font-family:\"Comic Sans MS\", cursive, sans-serif;\r\n");
      out.write("	padding-left:90px;\r\n");
      out.write("}\r\n");
      out.write("#Footer2 {\r\n");
      out.write("  display:flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  padding: 10px 16px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background: #14141f;\r\n");
      out.write("  color:white;\r\n");
      out.write("  margin-bottom:50px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("#Footer2 ul.style {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  padding-bottom:40px;\r\n");
      out.write("}\r\n");
      out.write("#Footer2 li a{\r\n");
      out.write("	color: white;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  padding: 14px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("#Footer2 li a:hover {\r\n");
      out.write("  color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Footer2 .Txtstyle{\r\n");
      out.write("	font-family:\"Comic Sans MS\", cursive, sans-serif;\r\n");
      out.write("	font-size:24px;\r\n");
      out.write("	line-height: 1.8;\r\n");
      out.write("}\r\n");
      out.write("#Footer2 .Txtstyle2{\r\n");
      out.write("	padding-top:90px;\r\n");
      out.write("	font-family:\"Comic Sans MS\", cursive, sans-serif;\r\n");
      out.write("	font-size:24px;\r\n");
      out.write("	line-height: 1.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Footer2 ul.proFBBt {\r\n");
      out.write("  background-color: #00cc00;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 20px 50px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Footer2 .btpadding{\r\n");
      out.write("	padding-top:50px;\r\n");
      out.write("	padding-left:20px;\r\n");
      out.write("}\r\n");
      out.write("/*============================================================================*/\r\n");
      out.write("\r\n");
      out.write("h1.Ttxtstyle{\r\n");
      out.write("	color:white;\r\n");
      out.write("	font-family:\"Arial Black\", Gadget, sans-serif;\r\n");
      out.write("	text-shadow:1px 1px 2px black, 0 0 25px black, 0 0 5px black;\r\n");
      out.write("	font-size:60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("	padding:20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*DIV sections*/\r\n");
      out.write(".row {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("  margin: 0 -16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".col-25 {\r\n");
      out.write("  flex: 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-50,\r\n");
      out.write(".coll-50 {\r\n");
      out.write("   flex: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-75 {\r\n");
      out.write("  flex: 75%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-25,\r\n");
      out.write(".col-50,\r\n");
      out.write(".col-75 {\r\n");
      out.write("  padding: 20px 16px;\r\n");
      out.write("}\r\n");
      out.write("/*--------------------------------------------------------------------------------------*/\r\n");
      out.write("/*Form*/\r\n");
      out.write("fieldset{\r\n");
      out.write("	padding:20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("legend{\r\n");
      out.write("	font-size:22px;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle1.style2{\r\n");
      out.write("	font-family:\"Arial Black\", Gadget, sans-serif;\r\n");
      out.write("	font-size:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle1 label,\r\n");
      out.write("#formStyle3 label {\r\n");
      out.write("  display: block;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  float:left;\r\n");
      out.write("  margin-left:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle4 label{\r\n");
      out.write("  float:center;\r\n");
      out.write("  display: block;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  margin-left:10px;\r\n");
      out.write("  margin-bottom:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle2 label{ \r\n");
      out.write("	 font-family: \"Comic Sans MS\", cursive, sans-serif;\r\n");
      out.write("	 font-weight:bold;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    line-height: 1.15;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("	 width:100%;\r\n");
      out.write("}\r\n");
      out.write("#formStyle6 input[type=text],\r\n");
      out.write("#formStyle6 input[type=email],\r\n");
      out.write("#formStyle3 input[type=email],\r\n");
      out.write("#formStyle3  input[type= password],\r\n");
      out.write("#formStyle1  input[type= password],\r\n");
      out.write("#formStyle1  input[type= number],\r\n");
      out.write("#formStyle1 input[type=file],\r\n");
      out.write("#formStyle1 input[type=number]\r\n");
      out.write("#formStyle4 input[type=email],\r\n");
      out.write("#formStyle1 input[type=email],\r\n");
      out.write("#formStyle1 input[type=month],\r\n");
      out.write("#formStyle1 input[type=date],\r\n");
      out.write("#formStyle1 input[type=text],\r\n");
      out.write("#formStyle1 input[type=tel],\r\n");
      out.write("#formStyle3 input[type=text],\r\n");
      out.write("#formStyle4 input[type=tel],\r\n");
      out.write("#formStyle4 input[type=text],\r\n");
      out.write("#formStyle1 select{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  border: 2px solid #ccc;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle6 input:active[type=text],\r\n");
      out.write("#formStyle6 input:active[type=email],\r\n");
      out.write("#formStyle3  input:active[type= password],\r\n");
      out.write("#formStyle3  input:active[type= email],\r\n");
      out.write("#formStyle1 input:active[type=file],\r\n");
      out.write("#formStyle1 input:active[type=number],\r\n");
      out.write("#formStyle1 input:active[type=month],\r\n");
      out.write("#formStyle1 input:active[type=text],\r\n");
      out.write("#formStyle3 input:active[type=text],\r\n");
      out.write("#formStyle4 input:active[type=text],\r\n");
      out.write("#formStyle4 input:active[type=text],\r\n");
      out.write("#formStyle1 select:active{\r\n");
      out.write("    border: 2px solid #808080;\r\n");
      out.write("	outline:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle3  input[type= radio]{\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  margin-left:20px;\r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write("#formStyle6 textarea,\r\n");
      out.write("#formStyle1 textarea{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  height:80px;\r\n");
      out.write("  font-family:Verdana;\r\n");
      out.write("  border-radius:50px;\r\n");
      out.write("  outline:none;\r\n");
      out.write("  resize: vertical;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle1 form,\r\n");
      out.write("#formStyle2 form,\r\n");
      out.write("#formStyle3 form,\r\n");
      out.write("#formStyle4 form{\r\n");
      out.write("	padding:20px;\r\n");
      out.write("	background-color: rgba(255, 255, 255,0.5);\r\n");
      out.write("	font-size:14px;\r\n");
      out.write("	font-family:Verdana;\r\n");
      out.write("	color:black;\r\n");
      out.write("	margin:20px;\r\n");
      out.write("	box-shadow:1px 1px 2px black, 0 0 25px black, 0 0 5px black;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	border:none;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("#formStyle6 form{\r\n");
      out.write("	font-size:14px;\r\n");
      out.write("	font-family:Verdana;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	border:none;\r\n");
      out.write("	padding:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle1 form,\r\n");
      out.write("#formStyle4 form{\r\n");
      out.write("	width:99%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle2 form{\r\n");
      out.write("	width:95%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formStyle3 form{\r\n");
      out.write("	width:50%;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	position:center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".Btn,\r\n");
      out.write(".Btn1,\r\n");
      out.write(".Btn2,\r\n");
      out.write(".Btn3,\r\n");
      out.write(".Btn4,\r\n");
      out.write(".Btn5{\r\n");
      out.write("\r\n");
      out.write("	padding:20px 30px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  background-color: #680000;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 30px;\r\n");
      out.write("  box-shadow: 0 5px #999;\r\n");
      out.write("  margin-bottom:30px;\r\n");
      out.write("  margin-top:10px;\r\n");
      out.write("  margin-left:20px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".Btn:active,\r\n");
      out.write(".Btn1:active,\r\n");
      out.write(".Btn3:active,\r\n");
      out.write(".Btn2:active,\r\n");
      out.write(".Btn4:active,\r\n");
      out.write(".Btn5:active,\r\n");
      out.write(".Btn6:active{\r\n");
      out.write("	background-color: #ff6a6f;\r\n");
      out.write("  box-shadow: 0 3px #666;\r\n");
      out.write("  transform: translateY(4px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Btn:hover,\r\n");
      out.write(".Btn1:hover,\r\n");
      out.write(".Btn3:hover,\r\n");
      out.write(".Btn2:hover,\r\n");
      out.write(".Btn4:hover,\r\n");
      out.write(".Btn5:hover{\r\n");
      out.write("	background-color: #ff6a6f\r\n");
      out.write("}\r\n");
      out.write(".Btn,\r\n");
      out.write(".Btn1{\r\n");
      out.write("	float:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Btn2{\r\n");
      out.write("	float:left;\r\n");
      out.write("}\r\n");
      out.write(".Btn3{\r\n");
      out.write("	margin-bottom:20px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".Btn4{\r\n");
      out.write("	margin-left:10px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Btn5{\r\n");
      out.write("	width:95%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form1{\r\n");
      out.write("	border:5px solid #565051;\r\n");
      out.write("	padding:20px;\r\n");
      out.write("	width:1000px;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	background:rgb(300, 300, 300);\r\n");
      out.write("	opacity: 0.85;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form2{\r\n");
      out.write("	border:5px solid #565051;\r\n");
      out.write("	padding:30px;\r\n");
      out.write("	width:750px;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	background:rgb(300, 300, 300);\r\n");
      out.write("	opacity: 0.85;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#paymentlist {\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#paymentlist td, #paymentlist th {\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#paymentlist tr:nth-child(even){background-color: #f2f2f2;}\r\n");
      out.write("\r\n");
      out.write("#paymentlist th {\r\n");
      out.write("  padding-top: 12px;\r\n");
      out.write("  padding-bottom: 12px;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  margin: 2px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover {background-color: #3e8e41}\r\n");
      out.write("\r\n");
      out.write(".input {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".qwe {\r\n");
      out.write("	padding-top: 12px;\r\n");
      out.write("  	padding-bottom: 12px;\r\n");
      out.write("  	text-align: left;\r\n");
      out.write("  	background-color: #04AA6D;\r\n");
      out.write("  	color: white;\r\n");
      out.write("  	\r\n");
      out.write("}\r\n");
      out.write(".qwe {\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".qwe td, .qwe th {\r\n");
      out.write("  \r\n");
      out.write("  padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttons {\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  margin: 2px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttons:hover {background-color: #3e8e41}\r\n");
      out.write("\r\n");
      out.write(".lable {\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".h2 {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>payment list</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"form1\">	\r\n");
      out.write("	<center><h2 class=\"h2\">List of Payments</h2></center>\r\n");
      out.write("	<a href=\"");
      out.print(request.getContextPath());
      out.write("/new\" class=\"btn btn-success\">\r\n");
      out.write("	<button type=\"submit\" class=\"button\">Add New Payment</button>\r\n");
      out.write("	</a>\r\n");
      out.write("	<br>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table id=\"paymentlist\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>ID</th>\r\n");
      out.write("		<th>Card Name</th>\r\n");
      out.write("		<th>Card Number</th>\r\n");
      out.write("		<th>Amount</th>\r\n");
      out.write("		<th>Year</th>\r\n");
      out.write("		<th>Month</th>\r\n");
      out.write("		<th>CVC</th>\r\n");
      out.write("		<th>Actions</th>\r\n");
      out.write("	</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<footer style=\"display: block;\r\n");
      out.write("  width:100%;\r\n");
      out.write("  height:auto;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  position:fixed;\">\r\n");
      out.write("<div class=\"FtopPadding\">\r\n");
      out.write("				<p class=\"copyRSing\" >Copyright &#169; 2021 - Online Movie & Tv Series System - All Right Reserved</p>\r\n");
      out.write("			</div>	\r\n");
      out.write("</footer>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /payments/payment-list.jsp(44,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("payment");
      // /payments/payment-list.jsp(44,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/payments/payment-list.jsp(44,1) '${listPayment}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listPayment}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	<tr>\r\n");
            out.write("		<td>");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("		<td>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("		<td>");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("		<td>");
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("		<td>");
            if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("		<td>");
            if (_jspx_meth_c_005fout_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("		<td>");
            if (_jspx_meth_c_005fout_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("		<td>\r\n");
            out.write("			<a href=\"edit?id=");
            if (_jspx_meth_c_005fout_005f7(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\">\r\n");
            out.write("			<button class=\"button\" type=\"submit\">\r\n");
            out.write("				Edit\r\n");
            out.write("			</button>\r\n");
            out.write("			</a> \r\n");
            out.write("			\r\n");
            out.write("			<a href=\"delete?id=");
            if (_jspx_meth_c_005fout_005f8(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\">\r\n");
            out.write("			<button class=\"button\" type=\"submit\" >\r\n");
            out.write("			Delete\r\n");
            out.write("			</button>\r\n");
            out.write("			</a> \r\n");
            out.write("		</td>\r\n");
            out.write("	</tr>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(46,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(47,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.cardname}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(48,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.cardnumber}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(49,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.amount}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(50,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.year}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(51,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.month}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f6_reused = false;
    try {
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(52,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.cvc}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      _jspx_th_c_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f7_reused = false;
    try {
      _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(54,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
      if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      _jspx_th_c_005fout_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f8_reused = false;
    try {
      _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /payments/payment-list.jsp(60,22) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payment.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
      if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      _jspx_th_c_005fout_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f8_reused);
    }
    return false;
  }
}
